

# Imagem do contêiner a ser implantada
# Substitua "my-repo" pelo nome do seu repositório
# Substitua "my-image" pelo nome da sua imagem
images:
  - "gcr.io/cnpj-analytics/container-teste/image-teste"
# Etapas de construção
steps:
  # Etapa 1: Construir a imagem do contêiner
  - name: "gcr.io/cloud-builders/docker"
    args: ["builds", "submit", "--tag", "gcr.io/cnpj-analytics/container-teste/image-teste", "."]

  # Etapa 2: Implantar a imagem do contêiner no Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["run", "deploy", "container-genai-teste", "--image", "gcr.io/cnpj-analytics/container-teste/image-teste", "--region", "us-central1", "--allow-unauthenticated",  "--platform", "managed"]
#