# cloudbuild.yaml para implantação contínua do Cloud Run

apiVersion: v1

# Nome do projeto do Google Cloud
projectId: "cnpj-analytics"

# Imagem do contêiner a ser implantada
# Substitua "my-repo" pelo nome do seu repositório
# Substitua "my-image" pelo nome da sua imagem
images:
  - "gcr.io/cnpj-analytics/container-test/image-test"

# Gatilho de implantação contínua
# Este gatilho será acionado sempre que houver um push para o branch "main"
triggers:
  - event: google.github.push
    branch: main

# Etapas de construção
steps:
  # Etapa 1: Construir a imagem do contêiner
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${images[0].name}", "."]

  # Etapa 2: Implantar a imagem do contêiner no Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["run", "deploy", "container-genai-test", "--image", "${images[0].name}", "--platform", "managed"]
